### ISSUE TITLE
Gov Healey parking minimums 

### ISSUE THREAD

**Issue by eamondawes** [tjrileywisc/waltham_gis#27]
In your MBTA zoning changes investigation, you say that Healey's proposal is to remove all parking minimums within 1/2 of transit. Many articles have been poorly written, but that would only apply to ADUs within 1/2 mile, not all housing types.

**Comment by tjrileywisc** [comment]
I probably saw one of those poorly written articles... It really did seem too good to be true.

It can definitely be removed or at least fixed up to be more accurate.
